### ISSUE TITLE
Trying install on Tiny pi like board

### ISSUE THREAD

**Issue by northwestfrog** [wifidog/wifidog-auth-laravel#38]
Hi,

Thank you for all your good work.

I have mostly managed to  install and configure wifidog-auth-laravel.

Since the installation to a Pi size like board (rock64 with debian buster, no desktop), There was a lot of missing components:

Had to install:
php and and apache depency for php
Composer
Apache2
Sqlite
Notejs

Had to add a dependency to  "tymon/jwt-auth", "^1.0" in the composer.json
Had to update the socialite dependency to sinkcup/laravel-ui-socialite in the composer.json
Had to perform an initial  "composer update mirrors" to fix issues with the "composer install"
Had to perform a2enmod rewrite for apache

After all of this, I do not see anything wrong except for the phpunit test that fails with the following error: 

Time: 2.15 seconds, Memory: 30.00 MB

There was 1 failure:

1) Tests\Feature\LoginControllerTest::testHandleProviderCallbackSuccess
Response status code [500] is not a redirect status code.
Failed asserting that false is true.

/home/jeanfrancois/wifidog-auth-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:166
/home/jeanfrancois/wifidog-auth-laravel/tests/Feature/LoginControllerTest.php:65

I dont know if it is ok or not in the context.

I cannot test the google-chrome command, because the setup is without a gui.
The curl with  ping command provides a pong output (was almost hidden)
When I run the curl command  with the chrome URL I get served an html page that contains the title Wifidog Auth, which sounds appropriate.

Is this issue with Unit Test denoting that there is still some dependency missing from my setup?

Best Regards

**Comment by sinkcup** [comment]
Thanks, @northwestfrog

this project doesn't use JWT yet, I am so sorry for forgetting to remove it from the doc.

ignore the warning:

> Package sinkcup/laravel-make-auth-socialite is abandoned, you should avoid using it. Use sinkcup/laravel-ui-socialite instead.

`sinkcup/laravel-ui-socialite` is for Laravel 6, `sinkcup/laravel-make-auth-socialite` is for Laravel 5.x, you don't need to update it.

the laravel-china.org composer mirror is down, I should not use any mirror in open source project, thanks for your bug report.

"a2enmod rewrite" should be added to the docs, you are right.

the 500 error is because of `sinkcup/laravel-make-auth-socialite` not support SQLite...and it's abandoned, so I upgrade this project to Laravel 6 now! you can only use MySql in this project now...

**Comment by sinkcup** [comment]
@northwestfrog I have upgraded this project to Laravel 6, and fixed the 500 error. you could try again.

**Comment by northwestfrog** [comment]
Will retry and provide feedback. Thanks

**Comment by northwestfrog** [comment]
I am experiencing some issues with mysql (since its now a requirement), more specifically with the password to use in the .env file. the artisan migrate command always fails with a failure to authenticate. the DB_PASSWORD=1 fails and I have attempted to change it to a series of other passwords with the same result.

**Comment by sinkcup** [comment]
you could use SQLite now, if you want to use MySQL, you should change the env config with your password.
